# fly.toml app configuration file generated for wild-sunset-3727 on 2023-11-01T20:01:22+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wild-sunset-3727"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 4523
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
