name: wetube-reloaded-mehr
app: node@20
options:
  env:
    - name: .ENV
      value: secret
  ports: "4523"
context:
  git:
    url: https://github.com/NoelKim714/wetube-reloaded-mehr.git
    branch: ctype